# _config.yml
title: "Martyn Notes"
author: Started in 2024
author_email: hi@martynnotes.com
baseurl: ""
url: "https://martynnotes.com"
theme: minima
footer_text: "martynnotes.com All rights reserved. 2024."
github_username: martynnotes
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-paginate


share-links-active:
  linkedin: true

rss-description: This website is a virtual proof that I'm awesome

excerpt_length: 100

# Whether or not to show an excerpt for every blog post in the feed page
feed_show_excerpt: true

# Whether or not to show a list of tags below each post preview in the feed page
feed_show_tags: true

# Add a search button to the navbar
post_search: true

# The keywords to associate with your website, for SEO purposes
keywords: "database,azure,sqlserver,sql,kql,infrastructure,ai,webapp,data,sqlmanagedinstance,azuresql,kusto,kustoquerylanguage"
