# _config.yml
title: "MartynNotes"
author: Martyn Rangel Figueiredo
author_email: hi@martynnotes.com
baseurl: ""
url: "https://martynnotes.com"
theme: minima
footer_text: "martynnotes.com All rights reserved. 2024."
