# _config.yml
title: "Iron Sentinel"
author: Martyn
author_email: martyn@ironsentinel.dev
baseurl: ""
url: "https://ironsentinel.dev"
theme: minima
footer_text: "ironsentinel.dev All rights reserved. 2024."
github_username: ironsentineldev
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-paginate


share-links-active:
  linkedin: true

rss-description: This website is a virtual proof that I'm awesome

excerpt_length: 100

# Whether or not to show an excerpt for every blog post in the feed page
feed_show_excerpt: true

# Whether or not to show a list of tags below each post preview in the feed page
feed_show_tags: true

# Add a search button to the navbar
post_search: true

# The keywords to associate with your website, for SEO purposes
keywords: "database,azure,sqlserver,sql,kql,infrastructure,ai,webapp,data,sqlmanagedinstance,azuresql,kusto,kustoquerylanguage"
