# _config.yml
title: "logs98"
author: by root
author_email: root@logs98.com
baseurl: ""
url: "https://rss.logs98.com"
theme: minima
footer_text: "logs98.com All rights reserved. 2024."
github_username: logs98
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
