# _config.yml
title: "Iron Sentinel"
author: 
author_email: martyn@ironsentinel.dev
baseurl: ""
url: "https://ironsentinel.dev"
theme: minima
footer_text: "ironsentinel.dev All rights reserved. 2024."
github_username: ironsentineldev
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap


share-links-active:
  linkedin: true
  reddit: true
  twitter: true
  email: true
